{% set name = "qiskit-experiments" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-experiments-{{ version }}.tar.gz
  sha256: 82d2c8fa59de72a224bd4ccd865f15a34ed3dc2967b05073be413089e2635853

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pandas >=1.1.5
    - qiskit >=0.45
    - rustworkx
    - lmfit
    - matplotlib-base >=3.4
    - numpy >=1.17
    - python >=3.8
    - qiskit-ibm-experiment >=0.4.6
    - scipy >=1.4
    - uncertainties

test:
  imports:
    - qiskit_experiments
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiskit-community/qiskit-experiments
  summary: Software for developing quantum computing programs
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: https://qiskit-community.github.io/qiskit-experiments/

extra:
  recipe-maintainers:
    - wshanks
    - BastianZim
